### ISSUE TITLE
Add hex form of Zarr colors to README?

### ISSUE THREAD

**Issue by rabernat** [zarr-developers/zarr-logo#1]
It would be great to get the two colors of the gradient displayed in hex form in the README file. Then it can easily be used in other contexts.

Thanks!

**Comment by joshmoore** [comment]
Good point. Will do once everything is settled, but the current version is:

```
      <stop
         id="stop12"
         stop-color="#e58077"
         offset="0" />
      <stop
         id="stop14"
         stop-color="#e57a77"
         offset="0.09" />
      <stop
         id="stop16"
         stop-color="#e46876"
         offset="0.21" />
      <stop
         id="stop18"
         stop-color="#e34b75"
         offset="0.35" />
      <stop
         id="stop20"
         stop-color="#e12374"
         offset="0.5" />
      <stop
         id="stop22"
         stop-color="#e01073"
         offset="0.56" />
      <stop
         id="stop24"
         stop-color="#bb1085"
         offset="1" />
```

**Comment by joshmoore** [comment]
Note: having this & the SVG may be sufficient to not need to generate the gradient.png which is currently not working: https://github.com/zarr-developers/zarr-logo/releases/tag/2021-12-17

**Comment by joshmoore** [comment]
<img width="786" alt="Screenshot 2023-02-24 at 12 22 10" src="https://user-images.githubusercontent.com/88113/221167116-703e7626-7b58-46e8-bd17-c0507a2841a9.png">

:tada:
